// Generated by https://quicktype.io






export interface IZapato {
    cod:       string;
    tipo:    string;
    precio: number;
    thumbnailUrl: string;
    nombre: string;
}

// export interface IClientes: Cliente[];