// Generated by https://quicktype.io





export interface IEmpleado {
    nif:       string;
    nombre:    string;
    apellidos: string;
    telefono: number;
}

// export interface IClientes: Cliente[];